### ISSUE TITLE
Constructor with later filled strings with ID and friendly name

### ISSUE THREAD

**Issue by proasnet** [paulino/ha-mqtt-entities#1]
dear @paulino ,
thank you for your library. I am trying it to my project.

Please, can you help me with use it?
In your examples, the constructor has some defined macros
```
#define HA_DEVICE_ID   "example04"
#define HA_DEVICE_FRIENDLY_NAME "Example Numeric-Sensor HA-MQTT"

HADevice ha_device = HADevice(HA_DEVICE_ID,HA_DEVICE_FRIENDLY_NAME,"1.0");
```

but in my project, the unique ID and friendly name will be filled in a setup from a strings.

How can I do it?

Thank you.

**Comment by paulino** [comment]
The  problem is that the strings are not copied in object instances, they use a reference (const char * pointer)

The best way is to use global char* strings (which are not allocated in the context function stack). In your setup function, it is possible to allocate memory for global strings and copy them.
Anyway, dynamic memory allocation/deallocation is not recommended due to fragmentation of heap memory. 

But if the setup function is called a few times, there is no problem.

An example:

``` c
#define ENTITIES_COUNT 1
String device_id;
String device_desc;
// Using pointers for dynamic configuration
HADevice *ha_device ;
HANumber *ha_number ;

void setup() {

    device_id = "My device";
    device_desc = "My device description";

    ha_device = new HADevice(device_id.c_str(),device_desc.c_str(),"1.0");
    ha_number = new HANumber("example01number","Slicer",*ha_device,1,100,1);
    
    HAMQTT.addEntity(*ha_number);
    ha_number->setState(50);


}
```

**Comment by proasnet** [comment]
Thank you @paulino .
In the meantime, a colleague advised me and edited your library.

In the hadevice.h file
protected was changed to public and everything now works as it should

In the global is
`HADevice ha_device = HADevice( "" , "" , SW_VER );`

In the setup() is
```
ha_device.identifier = exchange_data.serial_number.c_str();
ha_device.name = exchange_data.serial_number.c_str();
```

**Comment by proasnet** [comment]
Problem solved.
Your library I move from Arduino/Libraries to a local sketch folder.
Maybe you will add a feature in the future
set uniqueid and set name that will be used in setup().
Then I won't use the local library in the sketch folder.

Looking forward to more features
Availability
Binary Sensor
Icons, class
Manufacturer and model for hadevice

Thank you very much

**Comment by paulino** [comment]
I think this feature is need, I'll add in next version
