### ISSUE TITLE
Number input as a input field box

### ISSUE THREAD

**Issue by proasnet** [paulino/ha-mqtt-entities#5]
Dear @paulino ,
I have one more request for you. Is it possible to fill in the Input Number not as a slider, but as an input number field?
![obrázok](https://github.com/user-attachments/assets/b36cd953-24f2-4c3c-a688-8242b633ca88)

Thank you

**Comment by paulino** [comment]
I think when the feature `mode` is set to `box` HA uses a box:

``` cpp
 ha_number.addFeature("mode","box");
```

but I haven't tested it ...

**Comment by proasnet** [comment]
Dear @paulino , its working fine. Thank you.

**Comment by proasnet** [comment]
Can the unit also be set? For example, "%" or "m/s" etc...?
`HANumber( "set_speed_m1_normal" , "S-00 M1 Normal (S)" , ha_device , 0 , 100 , 1, "m/s" );`


```
    public:
        HANumber(const char *unique_id, const char *name,
            HADevice& device, int min, int max, int step , const char *units);
        HANumber(const char *unique_id, const char *name, int min, int max,
            int step , const char *units);
```
